export enum PATHS {
  HOME = "/",
  LOGIN = "/login",
  FORGET_PASS = "/forget-password",
  REGISTER = "/register",
  VERIFY="/verify",
  CHARITIES = "charities",
  BRANDS = "brands",
  BOARD_ROOM = "board-room",
  //COURSES = "courses",
  CURRICULUM = "curriculum",
  SETTINGS = "settings",
  MEMBER = "member",
  MEMBER_PROFILE = "profile",
  MEMBER_DASHBOARD = "dashboard",
  MEMBER_NOTIFICATIONS = "notifications",
  MEMBER_INVENTORY = "inventory",
  MEMBER_COMMISSION = "commission",
  MEMBER_EXPERIENCE = "experience",
  MEMBER_PARTICIPATION = "participation",
  MEMBER_QUESTIONS = "questions",
  MEMBER_EVENTS = "events",
  MEMBER_LEVELS = "levels",
  MEMBER_BADGES = "badges",
  MEMBER_CHALLENGES = "challenges",
}

export enum ROUTES {
  HOME = "/",
  LOGIN = "/login",
  FORGET_PASS = "/forget-password",
  REGISTER = "/register",
  VERIFY="/verify",
  CHARITIES = "charities",
  BRANDS = "brands",
  BOARD_ROOM = "board-room",
  //COURSES = "courses",
  CURRICULUM = "curriculum",
  SETTINGS = "settings",
  MEMBER_PROFILE = "member/profile",
  MEMBER_DASHBOARD = "member/dashboard",
  MEMBER_COMMISSION = "member/commission",
  MEMBER_EXPERIENCE = "member/experience",
  MEMBER_LEVELS = "member/levels",
  MEMBER_BADGES = "member/badges",
  MEMBER_CHALLENGES = "member/challenges",
  MEMBER_NOTIFICATIONS = "member/notifications",
  MEMBER_INVENTORY = "member/inventory",
  MEMBER_PARTICIPATION = "member/participation",
  MEMBER_QUESTIONS = "member/questions",
  MEMBER_EVENTS = "member/events",
}
